# Generated by Django 5.0.9 on 2024-11-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, default='', max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, default='', max_length=12, null=True, unique=True, verbose_name='RG')),
                ('cnpj', models.CharField(blank=True, default='', max_length=20, null=True, unique=True, verbose_name='CNPJ')),
                ('cro', models.CharField(blank=True, default='', max_length=10, null=True, unique=True, verbose_name='CRO')),
                ('datanasc', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Nº')),
                ('complemento', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('uf', models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Celular')),
                ('whatsapp', models.BooleanField()),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='E-mail')),
                ('instagram', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': '1.1- Cadastro',
            },
        ),
    ]
