# Generated by Django 5.0.9 on 2024-11-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(default='', max_length=50, verbose_name='Marca')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Logomarca')),
                ('revenda', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Revenda')),
                ('cnpj', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='CNPJ')),
                ('endereco', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Nº')),
                ('complemento', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': '2.1- Marcas',
            },
        ),
    ]
