# Generated by Django 5.0.9 on 2024-11-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='marcas/', verbose_name='Logomarca'),
        ),
    ]
