# Generated by Django 5.0.9 on 2024-11-30 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_marca_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='email',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='revenda',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='uf',
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grupo', models.CharField(default='', max_length=50, verbose_name='Grupo')),
                ('idmarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': '2.2- Grupos',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('produto', models.CharField(default='', max_length=50, verbose_name='Produto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('idgrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.grupo', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': '2.3- Produtos',
            },
        ),
    ]
