# Generated by Django 5.0.9 on 2024-12-01 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimarcas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo2',
            name='idperiferico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimarcas.periferico', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='periferico',
            name='periferico',
            field=models.CharField(default='', max_length=50, verbose_name='Periférico'),
        ),
    ]
