# Generated by Django 5.0.9 on 2024-12-01 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('estoque', '0004_alter_produto_preco'),
        ('multimarcas', '0002_alter_grupo2_idperiferico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('numero', models.CharField(max_length=10, verbose_name='Nº Orçamento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total')),
                ('status', models.CharField(blank=True, choices=[('Em Andamento', 'Em Andamento'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Cancelado', 'Cancelado')], default='Em Andamento', max_length=20, null=True, verbose_name='Status')),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': '4.1- Orçamentos',
            },
        ),
        migrations.CreateModel(
            name='OrcamentoItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Desconto')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('idorcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamentos.orcamento', verbose_name='Orçamento')),
                ('idproduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto', verbose_name='Produto')),
                ('idproduto2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimarcas.produto2', verbose_name='Periférico')),
            ],
            options={
                'verbose_name': 'Itens do Orçamento',
                'verbose_name_plural': '4.2- Itens do Orçamento',
            },
        ),
    ]
