# Generated by Django 5.0.9 on 2024-12-02 22:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='data',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
