# Generated by Django 5.0.9 on 2024-12-03 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_produto_preco'),
        ('multimarcas', '0002_alter_grupo2_idperiferico_and_more'),
        ('orcamentos', '0002_alter_orcamento_data_alter_orcamento_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoitem',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Desconto'),
        ),
        migrations.AlterField(
            model_name='orcamentoitem',
            name='idproduto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='orcamentoitem',
            name='idproduto2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multimarcas.produto2', verbose_name='Periférico'),
        ),
        migrations.AlterField(
            model_name='orcamentoitem',
            name='quantidade',
            field=models.IntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='orcamentoitem',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='orcamentoitem',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Preço Unit.'),
        ),
    ]
